[workspace]
members = [
  "crates/platform",
  "crates/engine-core",
  "crates/gfx-wgpu",
  "crates/ui-core",
  "crates/shader-core",
  "demos/triangle",
]
resolver = "2"

[workspace.dependencies]
wgpu = "25.0.2"
